[package]
name = "kodex-exec-server-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "kodex_exec_server_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
kodex-file-system = { workspace = true }
kodex-network-proxy = { workspace = true }
kodex-protocol = { workspace = true }
kodex-shell-command = { workspace = true }
kodex-utils-path-uri = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision", "raw_value"] }

[target.'cfg(windows)'.dependencies]
kodex-mxc-sandbox = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
