[package]
name = "kodex-linux-sandbox"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kodex-linux-sandbox"
path = "src/main.rs"

[lib]
name = "kodex_linux_sandbox"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
clap = { workspace = true, features = ["derive"] }
kodex-install-context = { workspace = true }
kodex-network-proxy = { workspace = true }
kodex-process-hardening = { workspace = true }
kodex-protocol = { workspace = true }
kodex-sandboxing = { workspace = true }
kodex-uds = { workspace = true }
kodex-utils-absolute-path = { workspace = true }
globset = { workspace = true }
landlock = { workspace = true }
libc = { workspace = true }
rustix = { workspace = true }
seccompiler = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }

[target.'cfg(target_os = "linux")'.dev-dependencies]
kodex-core = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
test-case = "3.3.1"
tokio = { workspace = true, features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
