[package]
edition.workspace = true
license.workspace = true
name = "kodex-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
kodex-protocol = { workspace = true }
kodex-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
