[package]
edition.workspace = true
license.workspace = true
name = "kodex-home"
version.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
kodex-extension-api = { workspace = true }
kodex-utils-absolute-path = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
