[package]
edition.workspace = true
license.workspace = true
name = "kodex-extension-items"
version.workspace = true

[lib]
name = "kodex_extension_items"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
kodex-utils-absolute-path = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ts-rs = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
