load("//:defs.bzl", "kodex_rust_crate")

kodex_rust_crate(
    name = "core-plugins",
    compile_data = glob(
        include = ["**"],
        allow_empty = True,
        exclude = [
            "**/* *",
            "BUILD.bazel",
            "Cargo.toml",
        ],
    ),
    crate_name = "kodex_core_plugins",
)
